// REST tests for the chat room functionality

// valid and invalid tokens
@authTokenInvalid = "faketoken"
@authTokenValid = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVAbWUuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeW1kNlBQMk9PcU9HTXgvMEJjejcyLm00aUdPWFBidmJxR3RsWDkzWERqam9VUkVtRkphUUsiLCJpYXQiOjE3MTMyMTg2MjZ9.qIwi3nEe657Idg01_oYl1LvCq7jL6WeaGNrOsWDlNvY
###

// user posting for herself with valid token should succeed
POST http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

{
    "author": "jane@me.com",
    "text": "a random post for valid authenticated user"
}

###

POST http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

{
    "author": "jane@me.com"
    // Missing or empty text field
}

### 

POST http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

{
    // Missing or empty author field
    "text": "Hello, World!"
}


###

//token user and author mismatch
POST http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

{
    "author": "differentuser@example.com", 
    "text": "Hello, World!"
}

###
// non-existent user
POST http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

{
    "author": "nonexistentuser@example.com", 
    "text": "Hello, World!"
}

###
// invalid token
POST http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer {{authTokenInvalid}}

{
    "author": "nonexistentuser@example.com", 
    "text": "Hello, World!"
}

###
// get all messages
GET http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

###
// missing token type 1
POST http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer 

{
    "author": "nonexistentuser@example.com", 
    "text": "Hello, World!"
}

###
// missing token type 2
POST http://localhost:8080/chat/messages
Content-Type: application/json

{
    "author": "nonexistentuser@example.com", 
    "text": "Hello, World!"
}
